export const TO_DO_LIST_REQUEST='TO_DO_LIST_REQUEST'
export const TO_DO_LIST_SUCCESS='TO_DO_LIST_SUCCESS'
export const TO_DO_LIST_FAIL='TO_DO_LIST_FAIL'

export const TO_DO_CREATE_SUCCESS='TO_DO_CREATE_SUCCESS'

export const TO_DO_DETAILS_REQUEST='TO_DO_DETAILS_REQUEST'
export const TO_DO_DETAILS_SUCCESS='TO_DO_DETAILS_SUCCESS'
export const TO_DO_DETAILS_FAIL='TO_DO_DETAILS_FAIL'

export const TO_DO_UPDATE_SUCCESS='TO_DO_UPDATE_SUCCESS'

export const TO_DO_DELETE_SUCCESS='TO_DO_DELETE_SUCCESS'